name: C/C++ CI

on:
  push:
    branches: [ "mainc", "development", "experimental", "test*", "feat*", "bug*" ]
  pull_request:
    branches: [ "mainc", "development", "experimental", "test*", "feat*", "bug*" ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-22.04, ubuntu-latest, macos-latest, macos-14 ]
        python-version: [ "3.10", "3.12" ] # Note: 3.14 causes issues with Neuron 8.2.7

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version:  ${{ matrix.python-version }}

    - name: C++ info
      run: g++ -v

    - name: Install graphviz
      uses: ts-graphviz/setup-graphviz@v2
      with:
        # Skip to run brew update command on macOS.
        macos-skip-brew-update: 'true' # default false

    - name: Install dependencies (Ubuntu)
      run: sudo apt-get install -y tree graphviz openjdk-11-jdk cmake
      if: ${{ contains(matrix.runs-on, 'ubuntu') }}

    - name: Install dependencies (macOS)
      run: brew install tree cmake
      if: ${{ contains(matrix.runs-on, 'macos') }}

    - name: Build and install worm2d package (with C++ binaries)
      env:
        CMAKE_BUILD_PARALLEL_LEVEL: 4
      run: |
      
        pip install setuptools==80 # needed for Neuron on py >=3.12

        pip install -e .[dev] -v

    - name: Run C++ unit tests
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --target worm2d_tests worm2d_tests2
        ./build/tests

    - name: Test C++/Python interactions
      run: |
        cd tests/test_files
        ./test.sh
        cd modelspec_api
        ./test.sh

    - name: Test Python command line script
      run: |
        python -m worm2d.run_main -R 1233 -p 6 --doEvol --outputFolderName exampleRun2  # Note: small population of 6 for quick runtime

    - name: Test using test_all.sh
      run: |
        pip list

        pip install scikit_build_core # Needed for building C++ extensions with scikit-build &  --no-build-isolation

        export NEURON_HOME=$pythonLocation
        env

        ./test_all.sh 



    - name: list generated files
      run: |
          ls -alth
          tree
          pip list
